//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace FrebParserConsole
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class frebEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new frebEntities object using the connection string found in the 'frebEntities' section of the application configuration file.
        /// </summary>
        public frebEntities() : base("name=frebEntities", "frebEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new frebEntities object.
        /// </summary>
        public frebEntities(string connectionString) : base(connectionString, "frebEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new frebEntities object.
        /// </summary>
        public frebEntities(EntityConnection connection) : base(connection, "frebEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FrebLogDB> FrebLogDBs
        {
            get
            {
                if ((_FrebLogDBs == null))
                {
                    _FrebLogDBs = base.CreateObjectSet<FrebLogDB>("FrebLogDBs");
                }
                return _FrebLogDBs;
            }
        }
        private ObjectSet<FrebLogDB> _FrebLogDBs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FrebLogDBs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFrebLogDBs(FrebLogDB frebLogDB)
        {
            base.AddObject("FrebLogDBs", frebLogDB);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="frebModel", Name="FrebLogDB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FrebLogDB : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FrebLogDB object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static FrebLogDB CreateFrebLogDB(global::System.Int32 id)
        {
            FrebLogDB frebLogDB = new FrebLogDB();
            frebLogDB.ID = id;
            return frebLogDB;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Filename
        {
            get
            {
                return _Filename;
            }
            set
            {
                OnFilenameChanging(value);
                ReportPropertyChanging("Filename");
                _Filename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Filename");
                OnFilenameChanged();
            }
        }
        private global::System.String _Filename;
        partial void OnFilenameChanging(global::System.String value);
        partial void OnFilenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Provider
        {
            get
            {
                return _Provider;
            }
            set
            {
                OnProviderChanging(value);
                ReportPropertyChanging("Provider");
                _Provider = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Provider");
                OnProviderChanged();
            }
        }
        private global::System.String _Provider;
        partial void OnProviderChanging(global::System.String value);
        partial void OnProviderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventID
        {
            get
            {
                return _EventID;
            }
            set
            {
                OnEventIDChanging(value);
                ReportPropertyChanging("EventID");
                _EventID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventID");
                OnEventIDChanged();
            }
        }
        private global::System.String _EventID;
        partial void OnEventIDChanging(global::System.String value);
        partial void OnEventIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.String _Version;
        partial void OnVersionChanging(global::System.String value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FLevel
        {
            get
            {
                return _FLevel;
            }
            set
            {
                OnFLevelChanging(value);
                ReportPropertyChanging("FLevel");
                _FLevel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FLevel");
                OnFLevelChanged();
            }
        }
        private global::System.String _FLevel;
        partial void OnFLevelChanging(global::System.String value);
        partial void OnFLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OPcode
        {
            get
            {
                return _OPcode;
            }
            set
            {
                OnOPcodeChanging(value);
                ReportPropertyChanging("OPcode");
                _OPcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OPcode");
                OnOPcodeChanged();
            }
        }
        private global::System.String _OPcode;
        partial void OnOPcodeChanging(global::System.String value);
        partial void OnOPcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keywords
        {
            get
            {
                return _Keywords;
            }
            set
            {
                OnKeywordsChanging(value);
                ReportPropertyChanging("Keywords");
                _Keywords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Keywords");
                OnKeywordsChanged();
            }
        }
        private global::System.String _Keywords;
        partial void OnKeywordsChanging(global::System.String value);
        partial void OnKeywordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TimeCreated
        {
            get
            {
                return _TimeCreated;
            }
            set
            {
                OnTimeCreatedChanging(value);
                ReportPropertyChanging("TimeCreated");
                _TimeCreated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TimeCreated");
                OnTimeCreatedChanged();
            }
        }
        private global::System.String _TimeCreated;
        partial void OnTimeCreatedChanging(global::System.String value);
        partial void OnTimeCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.String _DateCreated;
        partial void OnDateCreatedChanging(global::System.String value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Computer
        {
            get
            {
                return _Computer;
            }
            set
            {
                OnComputerChanging(value);
                ReportPropertyChanging("Computer");
                _Computer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Computer");
                OnComputerChanged();
            }
        }
        private global::System.String _Computer;
        partial void OnComputerChanging(global::System.String value);
        partial void OnComputerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContextID
        {
            get
            {
                return _ContextID;
            }
            set
            {
                OnContextIDChanging(value);
                ReportPropertyChanging("ContextID");
                _ContextID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContextID");
                OnContextIDChanged();
            }
        }
        private global::System.String _ContextID;
        partial void OnContextIDChanging(global::System.String value);
        partial void OnContextIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LineNumber
        {
            get
            {
                return _LineNumber;
            }
            set
            {
                OnLineNumberChanging(value);
                ReportPropertyChanging("LineNumber");
                _LineNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LineNumber");
                OnLineNumberChanged();
            }
        }
        private global::System.String _LineNumber;
        partial void OnLineNumberChanging(global::System.String value);
        partial void OnLineNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ErrorCode
        {
            get
            {
                return _ErrorCode;
            }
            set
            {
                OnErrorCodeChanging(value);
                ReportPropertyChanging("ErrorCode");
                _ErrorCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ErrorCode");
                OnErrorCodeChanged();
            }
        }
        private global::System.String _ErrorCode;
        partial void OnErrorCodeChanging(global::System.String value);
        partial void OnErrorCodeChanged();

        #endregion
    
    }

    #endregion
    
}
